// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOFU3ihtHmlqDG3bzWMYkfjP1rjugpNnY',
    appId: '1:558660222330:web:78005da6e0bf9526ed2ac3',
    messagingSenderId: '558660222330',
    projectId: 'to-do-list-app-e0bed',
    authDomain: 'to-do-list-app-e0bed.firebaseapp.com',
    storageBucket: 'to-do-list-app-e0bed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQyIspeWr3C2_f26UWCdpaqVfcMVCMO1g',
    appId: '1:558660222330:android:404bc6bd247241bded2ac3',
    messagingSenderId: '558660222330',
    projectId: 'to-do-list-app-e0bed',
    storageBucket: 'to-do-list-app-e0bed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtNqyYsgjeiiLXKYD0vxvSNM06v-Ib0ig',
    appId: '1:558660222330:ios:8d7cfb9be3bde590ed2ac3',
    messagingSenderId: '558660222330',
    projectId: 'to-do-list-app-e0bed',
    storageBucket: 'to-do-list-app-e0bed.appspot.com',
    iosClientId: '558660222330-h1bgslds3a6g79u8sp2jipvejh9m2mn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtNqyYsgjeiiLXKYD0vxvSNM06v-Ib0ig',
    appId: '1:558660222330:ios:8d7cfb9be3bde590ed2ac3',
    messagingSenderId: '558660222330',
    projectId: 'to-do-list-app-e0bed',
    storageBucket: 'to-do-list-app-e0bed.appspot.com',
    iosClientId: '558660222330-h1bgslds3a6g79u8sp2jipvejh9m2mn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDo',
  );
}
